---
services:
  echo-server:
    image: istio/tcp-echo-server:latest
    container_name: echo-server
    restart: unless-stopped
    # ports:
      # - 5432:9000
    networks:
      - frontend
    labels:
     - traefik.enable=true
     - traefik.docker.network=frontend
     - traefik.tcp.routers.echo-server.tls=true
     - traefik.tcp.routers.echo-server.tls.passthrough=true
     - traefik.tcp.routers.echo-server.tls.certresolver=cloudflare
     - traefik.tcp.routers.echo-server.entrypoints=other
     - traefik.tcp.routers.echo-server.rule=HostSNI(`echo.home.webcap.site`)
     - traefik.tcp.services.echo-server.loadbalancer.server.port=9000
networks:
  frontend:
    external: true