services:
  web:
    image: odoo:18
    depends_on:
      - db
    volumes:
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    labels:
     - traefik.enable=true
     - traefik.docker.network=frontend
     - traefik.http.routers.odoo-server.tls=true
     - traefik.http.routers.odoo-server.tls.certresolver=cloudflare
     - traefik.http.routers.odoo-server.entrypoints=websecure
     - traefik.http.routers.odoo-server.rule=Host(`odoo.home.webcap.site`)
     - traefik.http.services.odoo-server.loadbalancer.server.port=8069
    environment:
      - HOST=pg-db
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - odoo
      - frontend
  db:
    image: postgres:15
    container_name: pg-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo
networks:
  odoo:
  frontend:
    external: true