---
services:
  nginx:
    image: docker.io/library/nginx:1.26.2-alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - frontend
    labels:
     - traefik.enable=true
     - traefik.http.routers.nginx.tls=true
     - traefik.http.routers.nginx.tls.certresolver=cloudflare
     - traefik.http.routers.nginx.entrypoints=websecure
     - traefik.http.routers.nginx.rule=Host(`nginx.home.webcap.site`)
networks:
  frontend:
    external: true