# We're going to use this verified comfyui image as a base
FROM ghcr.io/ai-dock/comfyui:latest-cuda

# Disable the authentication provided by the base image
ENV WEB_ENABLE_AUTH=false

# CMD ["./comfyui-api"]
