# We're going to use this verified comfyui image as a base
FROM ghcr.io/ai-dock/comfyui:v2-cuda-12.1.1-base-22.04-v0.2.0

# Disable the authentication provided by the base image
ENV WEB_ENABLE_AUTH=false

# CMD ["./comfyui-api"]
