---
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    # ports:
      # - "2181:2181"
    networks:
      - kafka

  kafka-server:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server
    restart: unless-stopped
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka.home.webcap.site:5432
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    volumes:
      - ./kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

    depends_on:
      - zookeeper
    networks:
      - kafka
      - frontend
    labels:
     - traefik.enable=true
     - traefik.docker.network=frontend
     - traefik.tcp.routers.kafka-server.tls=true
    #  - traefik.tcp.routers.kafka-server.tls.passthrough=true
     - traefik.tcp.routers.kafka-server.tls.certresolver=cloudflare
     - traefik.tcp.routers.kafka-server.entrypoints=other
     - traefik.tcp.routers.kafka-server.rule=HostSNI(`kafka.home.webcap.site`)
     - traefik.tcp.services.kafka-server.loadbalancer.server.port=9092

networks:
  kafka:
  frontend:
    external: true